object_classes = {"other": 0,
                  "alfalfa": 1,
                  "allium": 2,
                  "borage": 3,
                  "burdock": 4,
                  "calendula": 5,
                  "chickweed": 6,
                  "chicory": 7,
                  "chive_blossom": 8,
                  "coltsfoot": 9,
                  "common_mallow": 10,
                  "common_milkweed": 11,
                  "common_vetch": 12,
                  "common_yarrow": 13,
                  "coneflower": 14,
                  "cowslip": 15,
                  "crimson_clover": 16,
                  "crithmum_maritimum": 17,
                  "daisy": 18,
                  "fireweed": 19,
                  "gardenia": 20,
                  "garlic_mustard": 21,
                  "geranium": 22,
                  "ground_ivy": 23,
                  "harebell": 24,
                  "henbit": 25,
                  "knapweed": 26,
                  "mullein": 27,
                  "ramsons": 28,
                  "red_clover": 29,
                  "corn": 30,
                  "tomato": 31,
                  "apple_tree": 32,
                  "cassava": 33,
                  "pear_tree": 34,
                  "grape": 35,
                  "artichoke": 36,
                  "barbeton_daisy": 37,
                  "bee_balm": 38,
                  "bishop_of_llandaff": 39,
                  "bolero_deep_blue": 40,
                  "cautleya_spicata": 41,
                  "corn_poppy": 42,
                  "daffodil": 43,
                  "giant_white_arum_lily": 44,
                  "grape_hyacinth": 45,
                  "japanese_anemone": 46,
                  "lenten_rose": 47,
                  "orange_dahlia": 48,
                  "passion_flower": 49,
                  "siam_tulip": 50,
                  "spring_crocus": 51,
                  "toad_lily": 52,
                  "tree_mallow": 53,
                  "tree_poppy": 54,
                  "abies_lasiocarpa": 55,
                  "abies_sibirica": 56,
                  "abutilon_anglosomaliae": 57,
                  "abutilon_theophrasti": 58,
                  "acacia": 59,
                  "adiantum": 60,
                  "agastache_rugosa": 61,
                  "ageratum_houstonianum": 62,
                  "allium_angulosum": 63,
                  "allium_canadense": 64,
                  "allium_pervestitum": 65,
                  "allium_ramosum": 66,
                  "allium_tianschanicum": 67,
                  "alnus_glutinosa": 68,
                  "alopecurus_alpinus": 69,
                  "amaranthus_hybridus": 70,
                  "ambrosia": 72,
                  "anemone_altaica": 72,
                  "anemone_borealis": 73,
                  "anemone_debilis": 74,
                  "anemone_multifida": 75,
                  "anemone_parviflora": 76,
                  "anemone_quinquefolia": 77,
                  "anemone_sylvestris": 78,
                  "aristolochia_serpentaria": 79,
                  "artemisia_anethifolia": 80,
                  "artemisia_arctica": 81,
                  "betula_mandshurica": 82,
                  "bidens": 83,
                  "bistorta_officinalis": 84,
                  "boerhavia_coccinea": 85,
                  "cannabis": 86,
                  "cedrus_libani": 87,
                  "clematis_florida": 88,
                  "delphinium_elatum": 89,
                  "egeria_densa": 90,
                  "eleutherococcus_senticosus": 91,
                  "eschscholzia_californica": 92,
                  "eupatorium_rotundifolium": 93,
                  "gaillardia_pulchella": 94,
                  "geranium_pratense": 95,
                  "haracleum_ossethicum": 96,
                  "helianthus_tuberosus": 97,
                  "inula_britannica": 98,
                  "jasminum_polyanthum": 99,
                  "lepidium_draba": 100,
                  "lophanthus_anisatus": 101,
                  "magnolia_acuminata": 102,
                  "maianthemum_bifolium": 103,
                  "mespilus": 104,
                  "phalacroloma_strigosum": 105,
                  "phaseolus_vulgaris": 106,
                  "pinckneya_bracteata": 107,
                  "polygonum_aviculare": 108,
                  "polypodiophyta": 109,
                  "populus_nigra": 110,
                  "ranunculus_polyanthemos": 111,
                  "ranunculus_repens": 112,
                  "ranunculus_submarginatus": 113,
                  "rhodiola_rosea": 114,
                  "rumex_longifolius": 115,
                  "sigesbeckia_orientalis": 116,
                  "solanum_nigrum": 117,
                  "spiraea_media": 118,
                  "stipa_capillata": 119,
                  "taraxacum": 120,
                  "taraxacum_officinale": 121,
                  "tilia_cordata": 122,
                  "torreya_taxifolia": 123,
                  "verbesina_encelioides": 124,
                  "viola_arvensis": 125,
                  "soy": 126}

object_type = {"background": 0,
              "stem": 1,  
              "leaf": 2, 
              "fruit": 3,
              "flower": 4,
              "root": 5,
              "swimming_pool": 6,
              "field": 7,
              "building": 8,
              "tree": 9,
              "road": 10,
              "other": 11}

object_type_ru = {"фон": 0,
              "стебель": 1,  
              "лист": 2, 
              "фрукт": 3,
              "цветок": 4,
              "корень": 5,
              "бассейн": 6,
              "поле": 7,
              "здание": 8,
              "дерево": 9,
              "дорога": 10,
              "прочее": 11}

properties = {"condition": ["healthy", "dried", "diseased", "rotten", "partially damaged"],
              "type": ["herbaceous", "woody"],
              "ierarchy": ["main",  "side"],
              "group": ["single", "group"],
              "kind": ["flat", "other"],
              "ripeness": ["ripe", "unripe"],
              "stage": ["growing", "harvested", "packed"],
              "integrity": ["whole", "cutted"] 
             }


object_type2properties = {0: [],
                           1: ["condition", "type", "ierarchy"],
                           2: ["condition", "group", "kind"],
                           3: ["condition", "group", "ripeness", "stage", "integrity"],
                           4: ["condition", "group"],
                           5: ["condition", "group"],
                           6: ["condition", "group"],
                           7: ["condition", "group"],
                           8: ["condition", "group"],
                           9: ["condition", "group"],
                           10: ["condition", "group"],
                           11: ["condition", "group"]}


